### PR TITLE
[c++]lucky_pair_chalti.cpp

### PR DESCRIPTION
**Pull request by chaltidutta**
My  PR checks all the below points :-

- [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Comment by anjali1903** [comment]
Good work done but the recursion approach has a really bad Time Complexity. Could you optimize it?

**Comment by chaltidutta** [comment]
The recursive approach's time complexity is O(n*n) . and their are two strings, how can i do it in less than n^2 complexity ?

**Comment by anjali1903** [comment]
You can do it in O(n^2) by using the memoization technique.

**Comment by chaltidutta** [comment]
I have done it in O(n^2) .

**Comment by anjali1903** [comment]
The algorithm has a Time Complexity of O(2^n)

**Comment by chaltidutta** [comment]
Sorry, apologizing, an miscomunication happend from my side.

**Pull request closed without merging**
