### PR TITLE
[CPP]climb_stair.cpp

### PR DESCRIPTION
**Pull request by sayantan1413**
- [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Comment by anjali1903** [comment]
1. There are 2 files added under 1 PR title. Please make separate PRs for each file.
2. Please correct the PR title according to the given instruction.

**Comment by sayantan1413** [comment]
I have deleted the Grouping so i think now only one PR of climb stair exist.

**Comment by anjali1903** [comment]
> 1. There are 2 files added under 1 PR title. Please make separate PRs for each file.
> 2. Please correct the PR title according to the given instruction.

Fix point 2 as well please.

**Comment by sayantan1413** [comment]
I have changed the PR title please verify it is ok or not.

**Pull request merged**
