### PR TITLE
[c++]5%_mean_chalti.cpp

### PR DESCRIPTION
**Pull request by chaltidutta**
My PR checks all the below points :-
 - [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

please ckeck it for once.

### CODE REVIEW

**Comment by anjali1903** [comment]
Check each point mention in the PR template(something like this [x])

**Comment by chaltidutta** [comment]
yes, I have changed it, now you can check .

**Comment by anjali1903** [comment]
> yes, I have changed it, now you can check .
put an x in the third bracket [x]

**Comment by anjali1903** [comment]
put an x in the third bracket [x]

**Pull request merged**
