### PR TITLE
Update [CPP]destroy_asteroid_csubhradipta.cpp

### PR DESCRIPTION
**Pull request by cSubhradipta**
Added code for destroy_asteroid in cpp

- [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Comment by anjali1903** [comment]
For A={-2,-2,-1,-2}, the expected output is {-2,-2,-1,-2}

**Comment by cSubhradipta** [comment]
> For A={-2,-2,-1,-2}, the expected output is {-2,-2,-1,-2}

Code updated. Passing all test cases successfully.

**Comment by anjali1903** [comment]
For A={-2,2,-1,-2}, the expected output is {-2}

**Comment by cSubhradipta** [comment]
> For A={-2,2,-1,-2}, the expected output is {-2}

Code updated.

**Comment by anjali1903** [comment]
Good work!

**Pull request merged**
