### PR TITLE
Update [CPP]malfunctioning_keyboard_csubhradipta.cpp

### PR DESCRIPTION
**Pull request by cSubhradipta**
Added code for malfunctioning_keyboard in cpp

- [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Review by shaillykeshari — CHANGES_REQUESTED** [review]
The code yields a wrong answer. Carefully have a look at the sample input and output of the question, and make necessary changes accordingly.

**Comment by cSubhradipta** [comment]
> The code yields a wrong answer. Carefully have a look at the sample input and output of the question, and make necessary changes accordingly.

Okay. But this code passing all sample test cases successfully.

**Comment by anjali1903** [comment]
for s="cccvvvuuddddrrrmmmmeeqqgglllljjjjjnnnnpppptttthhhhiiiiikkffawwwwobbbbssonnnnmmmmffkkkklllljjjjqqqqmmhhhjjjjjaaaaauuuuttggggvvvvvlllleeeebboooooqmmwwwww", answer should be "achijoqrvw"
Your code gives "wqovajhooaijrvc"

**Comment by cSubhradipta** [comment]
> for s="cccvvvuuddddrrrmmmmeeqqgglllljjjjjnnnnpppptttthhhhiiiiikkffawwwwobbbbssonnnnmmmmffkkkklllljjjjqqqqmmhhhjjjjjaaaaauuuuttggggvvvvvlllleeeebboooooqmmwwwww", answer should be "achijoqrvw"
> Your code gives "wqovajhooaijrvc"

Code updated. Now passing all sample test cases as well as this test case.

**Review by shaillykeshari — APPROVED** [review]
The code passed all test cases.

**Comment by shaillykeshari** [comment]
Your PR will be merged soon.

**Pull request merged**
