### PR TITLE
added Weird Sorting in C++

### PR DESCRIPTION
**Pull request by sayantan1413**
- [x]  Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x]  Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Comment by anjali1903** [comment]
The correct way to check the boxes in the template is [x]

**Comment by anjali1903** [comment]
Your pr says that you have added code for only weird_sorting but the commits show addition of file for climb_stairs as well. Please make the changes.

**Comment by anjali1903** [comment]
Try weird_sorting using a single loop. :)

**Comment by sayantan1413** [comment]
I have used one loop only like i have counted the number of 7,14,21 in the input loop and did all the operation in single loop only?

**Comment by anjali1903** [comment]
Ahh! My bad. Good work!

**Pull request merged**
