### PR TITLE
[c++]reverse(linkedlist_recursive)_chalti.cpp & reverse(linkedlist_3P)_chalti.cpp

### PR DESCRIPTION
**Pull request by chaltidutta**
My PR checks all the below points :-

- [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Comment by chaltidutta** [comment]
I have added two files under one PR, because the question is same, that's why . first one was recursive , so in that solution I have taken an extra function, which is not followed by template, and other one using three pointer. So please let me know, that should I have to change the recursive solution or not.

**Comment by anjali1903** [comment]
Your code works fine but only fails an edge case which is when n=0.

**Comment by chaltidutta** [comment]
Can you please provide me the expected output for n=0 ?

**Comment by anjali1903** [comment]
> Can you please provide me the expected output for n=0 ?

What is the output when Linked List is NULL?

**Comment by chaltidutta** [comment]
I have fixed the edge case n=0, now you can check it.

**Pull request merged**
