### PR TITLE
Java code for addition of two Binary numbers under String repo.

### PR DESCRIPTION
**Pull request by aeyshubh**
Hello ,saw this project and wanted to contribute.

### CODE REVIEW

**Comment by aeyshubh** [comment]
If any changes are required ,please let me know .

**Comment by anjali1903** [comment]
I'm sorry @ShubhamPatel33 but PRs cannot be merged until the Winter of Code begins. Thankyou.

**Comment by aeyshubh** [comment]
Oook , btw i am participating in Woc so it  can be my first contribution if
i get accepted.

**Comment by aeyshubh** [comment]
I have applied for Dsc Nsec

**Pull request closed without merging**
