### PR TITLE
Update [CPP]priority_tasks_csubhradipta.cpp

### PR DESCRIPTION
**Pull request by cSubhradipta**
Added code for priority_tasks in cpp

- [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Review by shaillykeshari — CHANGES_REQUESTED** [review]
The code yields a wrong answer. For the test case where the input is 5 4 3 2 1, the expected output is -1 5 5 5 5, but the code here yields -1 -1 -1 -1 5 as output. Please review the code logic and make the necessary changes.

**Comment by cSubhradipta** [comment]
> The code yields a wrong answer. For the test case where the input is 5 4 3 2 1, the expected output is -1 5 5 5 5, but the code here yields -1 -1 -1 -1 5 as output. Please review the code logic and make the necessary changes.

Code updated.

**Comment by anjali1903** [comment]
Good job. But the complexity is very high. Can you try to reduce it? 
Also it seems like you have used stack forcefully, the job could've been done without stack here. Think of a stack-based solution.

**Comment by cSubhradipta** [comment]
> Good job. But the complexity is very high. Can you try to reduce it?
> Also it seems like you have used stack forcefully, the job could've been done without stack here. Think of a stack-based solution.

Okay, I'll try.

**Comment by cSubhradipta** [comment]
> Good job. But the complexity is very high. Can you try to reduce it?
> Also it seems like you have used stack forcefully, the job could've been done without stack here. Think of a stack-based solution.

Code updated.

**Review by shaillykeshari — APPROVED** [review]
The code compiled successfully and passed all test cases. Your PR will be merged soon.

**Comment by anjali1903** [comment]
AMAZING work! :D

**Pull request merged**
