### PR TITLE
Adding java code for Push_Zero

### PR DESCRIPTION
**Pull request by codebook-2000**
The code for [Push Zero](https://github.com/dscnsec/DSC-NSEC-Algorithms/pull/20/commits/42641e9ff24a35ae2eef2b811fe1af448a367986)
- [X] Code is added in right directory(Folder).
- [X] Brief Description of Solution is given.
- [X] Time and Space Complexity is mentioned
- [X] Code is well indented.
- [X] Comments are clearly written wherever necessary
- [X] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Comment by anjali1903** [comment]
Good job done! But there are certain points I'd like to mention.
1. You need to add a pull request template and make a pr only if all the boxes in the template are checked. The template is given in the Contributing.md section
2. The code can be made more efficient by using constant space. Give it a try :)

**Comment by codebook-2000** [comment]
The code for [Push Zero](https://github.com/dscnsec/DSC-NSEC-Algorithms/pull/20/commits/42641e9ff24a35ae2eef2b811fe1af448a367986)
- [X] Code is added in right directory(Folder).
- [X] Brief Description of Solution is given.
- [X] Time and Space Complexity is mentioned
- [X] Code is well indented.
- [X] Comments are clearly written wherever necessary
- [X] Code is successfully compiled and passes all test cases.

**Comment by anjali1903** [comment]
Hey.. the category is Array. So can you do this without forming a new array or string? By maybe using two pointers?

**Comment by codebook-2000** [comment]
@anjali1903 Hey can you check if the above code meets all expectations?

**Comment by anjali1903** [comment]
Good work!

**Pull request merged**
