### PR TITLE
Solution of 5%_mean

### PR DESCRIPTION
**Pull request by djm-1**
This PR contains the solution of the problem **5%_mean**.
Solution includes :

- [x] Solution Approach

- [x] Time and Space Complexity

- [x] Detailed comments of each operation

- [x] Code

- [x] Successfully compiled and tested with given test cases and other test cases.

### CODE REVIEW

**Review by Vishal-raj-1 — CHANGES_REQUESTED** [review]
@djm-1  Your code is well descripted, approach is clearly explained, well formatted code and comment. 

> Time and Space Complexity is missing, kindly add that.

**Please write your PRs more descriptive like**

s

**Comment by djm-1** [comment]
Ok... I am re-submitting the PR after modifying the code. Thank you for suggesting to me.

**Comment by Vishal-raj-1** [comment]
what are you doing ? There is no need to close PR. Just Edit your first commit message OR take care from next time.

**Comment by djm-1** [comment]
ok.... I am not experienced that's why

**Comment by Vishal-raj-1** [comment]
s1
If you click on three dot button on the right side of your commit, then you edit your commit message.

**Review by Vishal-raj-1 — APPROVED** [review]

**Comment by djm-1** [comment]
Sir is it correct now?

**Comment by Vishal-raj-1** [comment]
> Sir is it correct now?

Its Awesome. Congrats for your first PR.

**Comment by anjali1903** [comment]
I'm sorry but there has been some confusion regarding reviewers here. Unfortunately, this pr cannot be merged. @Vishal-raj-1 please remove yourself as a reviewer. Only @theslytherin and I are the mentors of this repository. Hope this clears things up.

**Pull request closed without merging**
