### PR TITLE
Update [CPP] binary_add_csubhradipta.cpp

### PR DESCRIPTION
**Pull request by cSubhradipta**
Added code for binary_add in cpp

- [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Review by shaillykeshari — CHANGES_REQUESTED** [review]
The code is yielding a wrong answer when the test case is a = "0" and b = "0". The expected output is "0" but the code is giving "10" as output. Please review the code logic and make the necessary changes.

**Comment by cSubhradipta** [comment]
> The code is yielding a wrong answer when the test case is a = "0" and b = "0". The expected output is "0" but the code is giving "10" as output. Please review the code logic and make the necessary changes.

Code updated

**Comment by shaillykeshari** [comment]
For the test case a = "11" and b = "1", the expected output is "100" but the code is yielding the output "1101100". Please review the logic of the code once again.

**Comment by cSubhradipta** [comment]
> For the test case a = "11" and b = "1", the expected output is "100" but the code is yielding the output "1101100". Please review the logic of the code once again.

Done

**Comment by shaillykeshari** [comment]
> > For the test case a = "11" and b = "1", the expected output is "100" but the code is yielding the output "1101100". Please review the logic of the code once again.
> 
> Done

Everything is good to go! Your PR will be merged soon.

**Review by shaillykeshari — APPROVED** [review]
The code passed all test cases.

**Pull request merged**
