### PR TITLE
added weird sorting

### PR DESCRIPTION
**Pull request by m-e-r-l-i-n**
Added [this](https://github.com/m-e-r-l-i-n/DSC-NSEC-Algorithms/blob/arrays/1.%20Array/weird_sorting/WeirdSortingMerlin.cpp) code to the project. Kindly check if everything is in proper order.

- [x] Code is added in right directory(Folder).
- [x] Brief Description of Solution is given.
- [x] Time and Space Complexity is mentioned
- [x] Code is well indented.
- [x] Comments are clearly written wherever necessary
- [x] Code is successfully compiled and passes all test cases.

### CODE REVIEW

**Comment by anjali1903** [comment]
Good job done! But there are certain points I'd like to mention.
1. While adding the pull request template, please check all the boxes (something like this [x] )
2. The code can be made more efficient by using constant space. Give it a try :)

**Comment by m-e-r-l-i-n** [comment]
ok i m on it!

**Comment by m-e-r-l-i-n** [comment]
i made the necessary changes, kindly check

**Comment by anjali1903** [comment]
Good job.

**Pull request merged**
